#!/bin/bash

# Run meat-analysis with Plink

#SBATCH --partition=all,highmem
#SBATCH -J run_meta_sensitivity
#SBATCH --mail-type=ALL
#SBATCH --mail-user=c.ke@lumc.nl
#SBATCH --time=24:00:00 
#SBATCH --ntasks=4
#SBATCH --mem=128000MB

module load gwas/plink/1.90p
cd /exports/reum/CKe/Pipelinerun_withPC/RunMeta/noMAFfilter/

#array=(EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt)

plink --meta-analysis Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noEAC

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noVienna

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noPEAC

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noEARTHA

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noSERA

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noACPA

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noEIRA

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt  RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noEARTHB

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noRAMS

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noMadrid

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noLeeds

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noTacera

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Glasgow_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noManchester

plink --meta-analysis EAC_noNA_noMAFfilter_meta.txt Vienna_noNA_noMAFfilter_meta.txt PEAC_noNA_noMAFfilter_meta.txt EARTH_A_noNA_noMAFfilter_meta.txt SERA_noNA_noMAFfilter_meta.txt ACPA_noNA_noMAFfilter_meta.txt EIRA_noNA_noMAFfilter_meta.txt EARTH_B_noNA_noMAFfilter_meta.txt RAMS_noNA_noMAFfilter_meta.txt Madrid_noNA_noMAFfilter_meta.txt Leeds_noNA_noMAFfilter_meta.txt Tacera_noNA_noMAFfilter_meta.txt Manchester_noNA_noMAFfilter_meta.txt --out ./stabilityTest/PlinkMeta_withPC_noGlasgow













